name: Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    #runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          # "**" if for any recursive dir
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

            #- name:
            #run: |
            #sudo apt-get update && sudo apt-get install -y cmake g++ ninja-build

      - name: Configure
        run: |
          cmake -S test -B build/test \
          -DENABLE_TEST_COVERAGE=ON \
          -DTEST_INSTALLED_VERSION=OFF \
          -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: |
          cmake --build build/test

      - name: test
        run: |
          ctest --test-dir ./build/test --output-on-failure

      - name: collect code coverage
        run: |
          bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"



